# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Amin Rezaei
title: MSc in Biomedical Imaging | Prospective Ph.D. Researcher in Multi-Source Behavioral Data Analysis

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: AMINREZAEl
github_username:  aminrezaei-img
stackoverflow_username: "18346001"
linkedin_username: Amin-Rezaeii
email_address: amin.rezaei@hotmail.com

# Additional icon links
additional_links:
  - title: My Website
    icon: fas fa-globe   # This is the Font Awesome icon class for a globe icon (solid style)
    url: https://www.aminrezaei.ai/

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/Profile picture.png
about_content: | # this will include new lines to allow paragraphs
  I am an enthusiastic Biomedical Imaging master's graduate with a strong skill set in technical and interpersonal areas. My expertise encompasses health technology, machine learning, computer vision, and image & signal processing. My ultimate aim is to contribute to research and innovation that positively impacts people's lives.
  
  Currently, I am eagerly anticipating the start of an industrial Ph.D. fellowship in the [<mark>LABDA</mark>](https://labda-project.eu/index.html) (Learning Network for Advanced Behavioural Data Analysis) project, set to begin in October 2023. This prestigious fellowship is part of the MSCA (Marie SkÅ‚odowska-Curie Actions) Doctoral Network, funded under [Horizon Europe (2021-2027)](https://marie-sklodowska-curie-actions.ec.europa.eu/document/horizon-europe-work-programme-2021-2022-marie-sklodowska-curie-actions).
  
  My upcoming research will generally focus on the analysis of multi-source advanced behavioral data. Within this domain, I will have specific responsibilities, including presenting findings at (inter)national meetings/conferences, contributing to educational activities within the consortium, and publishing scientific articles resulting in a dissertation. 
  
  Additionally, I will be contributing to the LABDA toolbox of advanced analysis methods for sensor-based behavioral data, conducting feasibility tests with an improved multi-source movement behavior data collection method, and further developing a smartphone application to combine accelerometer data with contextual information from GPS and/or EMA functionality. 
  
  I will also assess the potential of enhancing behavioral classification accuracy using data from additional sources and implementing improved classification algorithms. Moreover, I will systematically evaluate existing multi-source movement behavior data methods that involve combining accelerometer data with other information to improve classification accuracy and add contextual insights.
  
  Through these research endeavors, I aspire to make meaningful contributions to the field of multi-source behavioral data analysis, paving the way for innovative applications and advancements that can improve people's lives and lead to meaningful changes in how we approach behavioral analysis. 

  As a research-driven and target-oriented individual, I am committed to bridging the gap between science and industry. My ultimate goal is to make a positive impact across various domains and advance our understanding of human behavior.

  I am thrilled to collaborate and share knowledge within the LABDA consortium, embarking on a transformative journey that pushes the boundaries of data analysis and contributes to human-centric research.

  Stay tuned for updates on my exciting journey as I embark on this research endeavor!

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Project name
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Company name
        sub_title: Job title
        caption: Date Range (eg. November 2016 - present)
        link: Link to company (optional)
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Description of role
  - title: ğŸ“ Education
    layout: list
    content:
      - layout: top-right
        title: Master of Science - Biomedical Imaging
        sub_title: University of Turku, Finland
        city: Turku
        country: Finland
        caption: 2020 - 2023
        quote: >
          .  .  .
        description: | # this will include new lines to allow paragraphs
          During my graduate studies, I had the opportunity to explore the captivating world of imaging technologies and their transformative applications in the field of biomedicine. Through a carefully crafted curriculum, I gained extensive knowledge and practical expertise in a diverse range of topics, spanning from cutting-edge imaging techniques to advanced biomedical instrumentation and bioimaging informatics. Immersed in this interdisciplinary journey, I honed my statistical skills and cultivated a keen understanding of how to derive valuable insights from complex biomedical data.

          One of the highlights of the program was the freedom to tailor my studies through selectable major courses. I chose to specialize in areas that ignited my curiosity, such as programming for image analysis and innovative design thinking. These experiences provided me with a solid foundation in utilizing artificial intelligence and sophisticated visualization tools to process, interpret, and present intricate biomedical information effectively.

          As I pursued my passion for merging technology and healthcare, I discovered the power of AI-driven imaging solutions in driving progress and revolutionizing patient care. The program not only expanded my technical prowess but also nurtured a profound appreciation for the profound impact of biomedical imaging on human well-being.

      - layout: top-left
        title: Azad University, Iran
        sub_title: BSc. Solid-state Physics
        caption: 2010 - 2015
        quote: >
              .  .  .
        description: | # this will include new lines to allow paragraphs
          My major coursework spanned a diverse array of intriguing subjects, enriching my understanding of the fundamental laws that govern the behavior of matter at the atomic and subatomic levels. The curriculum included essential courses such as Mathematical Methods for Physicists, Analytical Mechanics, Electronics, Electromagnetics, Quantum Mechanics, Acoustics, Signals, Semiconductors, and The Principles of Solid-State Physics, each contributing to the well-rounded knowledge base I possess.

          Beyond the comprehensive academic experience, the programme also offered me a valuable opportunity to cultivate and refine my analytical thinking and problem-solving skills. Armed with this experience, I approach complex problems with a comprehensive and open-minded perspective, which allows me to examine issues from multiple angles, recognize the interconnectedness of various factors, and formulate well-considered solutions.

          Overall, studying physics has taught me the value of perseverance and adaptability. Rather than being daunted by complexities, I have learned to embrace them as opportunities for growth and learning. This resilience, coupled with the ability to see the bigger picture, equips me to navigate through the most intricate of challenges with clarity and composure.
          
          
        
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      On a personal level, I am like a Swiss Army knife of reliability and collaboration. I am well-organized, detail-oriented, and always eager to tackle new challenges. I have a strong sense of initiative, which I believe is essential for problem-solving and skill development.

      Although I value teamwork, I am also comfortable working independently. My goal is not only to achieve personal success but also to help the team achieve success and make a significant impact. I thrive in challenging environments and enjoy taking on new and complex tasks.
      
      In my free time, I enjoy puzzles ğŸ§©, coding âŒ¨ï¸, finance ğŸ’¹, reading ğŸ“š, cooking ğŸ‘¨â€ğŸ³, and the outdoors ğŸŒ²ğŸŒ…ğŸ–ï¸ğŸš´âœˆï¸. Iâ€™m always seeking to expand my skills and knowledge ğŸ“ˆ. Please explore ğŸ” my site to learn more about my background, projects, and research interests ğŸ”¬. Iâ€™m open to collaborations ğŸ¤, so feel free to connect! ğŸ˜€

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
