# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Amin Rezaei
title: MSc in Biomedical Imaging | Prospective Ph.D. Researcher in Multi-Source Behavioral Data Analysis

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: AMINREZAEl
github_username:  aminrezaei-img
stackoverflow_username: "18346001"
linkedin_username: Amin-Rezaeii

# Additional icon links
additional_links:
- title: My Website
  icon: fas fa-globe   # This is the Font Awesome icon class for a globe icon (solid style)
  url: https://www.aminrezaei.ai/
  - title: Email me
  icon: fas fa-envelope   # This is the Font Awesome icon class for the envelope icon (solid style)
  url: mailto:Amin.Rezaei@hotmail.com
  
# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/Profile picture.png
about_content: | # this will include new lines to allow paragraphs
  I am a passionate master's graduate in Biomedical Imaging with strong technical and interpersonal skills. I have experience in health technology, machine learning, computer vision, and image & signal processing. I seek to make a positive impact on people's lives through research and innovation.
  
  Currently, I am a prospective Ph.D. candidate, eagerly anticipating the start of an industrial Ph.D. fellowship in the [<mark>LABDA</mark>](https://labda-project.eu/index.html) (Learning Network for Advanced Behavioural Data Analysis) project starting October 2023. 
  
  This prestigious fellowship is a part of the MSCA (Marie SkÅ‚odowska-Curie Actions) Doctoral Network, under [Horizon Europe (2021-2027)](https://marie-sklodowska-curie-actions.ec.europa.eu/document/horizon-europe-work-programme-2021-2022-marie-sklodowska-curie-actions).

  My upcoming research will generally focus on the analysis of multi-source advanced behavioral data where I will have specific responsibilities to:
  
    - Present findings at (inter)national meetings/conferences.
    - Contribute to educational activities within the consortium.
    - Report on findings by publishing scientific articles, resulting in a dissertation.
    - Contribute to the LABDA toolbox of advanced analysis methods for sensor-based behavioral data.    
    - Conduct a feasibility test with the improved multi-source movement behavior data collection method.
    - Further develop an existing smartphone application to be able to combine accelerometer data with contextual data collected using GPS and/or EMA functionality.
    - Assess the possibility of enhancing behavioral classification accuracy using data from additional sources and implement the improved classification algorithm.
    - Systematically assess the benefits and drawbacks of existing multi-source movement behavior data methods where accelerometer data are combined with other data to improve classification accuracy and/or add contextual information.

  Through these research endeavors, I aspire to make meaningful contributions to the field of multi-source behavioral data analysis, paving the way for innovative applications and advancements that can improve people's lives and lead to meaningful changes in how we approach behavioral analysis. 

  As a research-driven and target-oriented individual, I am committed to bridging the gap between science and industry. My ultimate goal is to make a positive impact across various domains and advance our understanding of human behavior.

  Through collaboration and knowledge sharing within the LABDA consortium, I am excited to be part of a transformative journey that pushes the boundaries of data analysis and contributes to the progress of human-centric research.

  Stay tuned for updates on my exciting journey as I embark on this research endeavor!

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Project name
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Company name
        sub_title: Job title
        caption: Date Range (eg. November 2016 - present)
        link: Link to company (optional)
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Description of role
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Institution name
        sub_title: Qualifications (eg. BA Performing Arts)
        caption: Date Range (eg. 2016 - 2019)
        quote: >
          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Description of qualification
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      On a personal level, I am like a Swiss Army knife of reliability and collaboration. I am well-organized, detail-oriented, and always eager to tackle new challenges. I have a strong sense of initiative, which I believe is essential for problem-solving and skill development.
      
      Although I value teamwork, I am also comfortable working independently. My goal is not only to achieve personal success but also to help the team achieve success and make a significant impact. I thrive in challenging environments and enjoy taking on new and complex tasks.
      
      In my free time, I enjoy puzzles ğŸ§©, data mining ğŸ–¥ï¸, finance ğŸ’¹, reading ğŸ“š, cooking ğŸ‘¨â€ğŸ³, and the outdoors ğŸŒ²ğŸŒ…ğŸ–ï¸ğŸš´âœˆï¸. Iâ€™m always seeking to expand my skills and knowledge ğŸ“ˆ. Please explore ğŸ” my site to learn more about my background, projects, and research interests ğŸ”¬. Iâ€™m open to collaborations ğŸ¤, so feel free to connect! ğŸ˜€

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
